# Generated by Django 6.0.4 on 2026-05-04 14:40

import buckets.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='密钥名称')),
                ('key_hash', models.CharField(max_length=128, verbose_name='密钥哈希')),
                ('prefix', models.CharField(max_length=8, verbose_name='密钥前缀')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='上次访问时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='桶名称')),
                ('is_public', models.BooleanField(default=False, verbose_name='公开访问')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '存储桶',
                'verbose_name_plural': '存储桶',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BucketFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('folder_path', models.CharField(blank=True, default='', max_length=500, verbose_name='目录路径')),
                ('file', models.FileField(upload_to=buckets.models.bucket_file_upload_to, verbose_name='文件')),
                ('size', models.BigIntegerField(default=0, verbose_name='文件大小(bytes)')),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=255, verbose_name='MIME类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='buckets.bucket', verbose_name='所属桶')),
            ],
            options={
                'verbose_name': '桶文件',
                'verbose_name_plural': '桶文件',
                'ordering': ['-created_at'],
                'unique_together': {('bucket', 'folder_path', 'name')},
            },
        ),
    ]
